# -*- coding: utf-8 -*-
"""
Module of LaueTools project: inverse pole figure (IPF) color maps of orientation matrices,
with the color key in the standard stereographic triangle (as in EBSD softwares, MTEX, ...)

IPF-A map: color of the crystal direction parallel to the sample axis A (X, Y or Z = sample normal),
brought by the Laue group symmetry into the fundamental sector (standard triangle) of the stereographic projection.
Colors: red, green, blue at the 3 corners of the triangle (TSL convention), e.g. for cubic crystals
red = [001], green = [101], blue = [111]

Frames (LaueTools conventions):

- UB (.fit files) maps the orthonormal crystal frame to the lab frame: q_lab = UB B0 G*
  orthonormal crystal frame (CrystalParameters.calc_B_RR): x // a*, y in (a*, b*) plane, z // c (c* x a*)
  (cubic, tetragonal, orthorhombic: x // a, y // b, z // c;  hexagonal: x // a* = [10-10], z // c = [0001])
- lab frame: x // incoming beam, z vertical (towards detector in top reflection geometry), y = z ^ x
- sample frame: q_sample = Rot q_lab with Rot = rotation of anglesample (40 deg at BM32) around y
  (LaueGeometry.fromlab_tosample()): Z sample = normal to sample surface, X sample in the surface plane
  tilted by anglesample from the incoming beam, Y sample = y lab.
  It is the frame of the sample-frame deviatoric strain written in .fit files (labelled 'sample2' there,
  computed by CrystalParameters.strain_from_crystal_to_sample_frame2()), NOT the XMAS/OR 'sample2' frame
  (which is rotated by 90 deg around Z). On BM32: xech = -Y sample, yech = X sample, zech = Z sample

Supported Laue groups: 'm-3m' (cubic), '6/mmm' (hexagonal), '-3m1' (trigonal, hexagonal axes, e.g. Al2O3),
'4/mmm' (tetragonal), 'mmm' (orthorhombic)

Typical use::

    import LaueTools.ipfmap as IPF
    group = IPF.laue_group_of_material('Zr')
    fig, axes, rgbmaps = IPF.plot_ipf_maps(ffs0.UB, invmapdims, group, mask=combinedconds)
"""
import itertools
from typing import Dict, Iterable, Optional, Sequence, Tuple, Union

import numpy as np
import matplotlib.pyplot as plt

from LaueTools import dict_LaueTools as DictLT
from LaueTools import generaltools as GT

DEG = np.pi / 180.

SAMPLE_AXES = {'x': np.array([1., 0, 0]), 'y': np.array([0, 1., 0]), 'z': np.array([0, 0, 1.])}


# --------------------------------------------------------------------------------------
#  LAUE GROUPS: symmetry operators and standard triangle
# --------------------------------------------------------------------------------------
def _rotz(angle_deg: float) -> np.ndarray:
    c, s = np.cos(angle_deg * DEG), np.sin(angle_deg * DEG)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1.]])


def _twofold(axis) -> np.ndarray:
    u = np.asarray(axis, dtype=float)
    u = u / np.linalg.norm(u)
    return 2 * np.outer(u, u) - np.eye(3)


def _closure(generators) -> np.ndarray:
    """group generated by generators (3x3 matrices)"""
    ops = [np.eye(3)]
    changed = True
    while changed:
        changed = False
        for op in list(ops):
            for gen in generators:
                new = gen @ op
                if not any(np.allclose(new, o, atol=1e-8) for o in ops):
                    ops.append(new)
                    changed = True
    return np.array(ops)


def _cubic_ops() -> np.ndarray:
    ops = []
    for perm in itertools.permutations(range(3)):
        for signs in itertools.product((1, -1), repeat=3):
            mat = np.zeros((3, 3))
            for row, (col, sign) in enumerate(zip(perm, signs)):
                mat[row, col] = sign
            ops.append(mat)   # 48 = 24 rotations x inversion
    return np.array(ops)


def _hexdir(phi_deg):
    return np.array([np.cos(phi_deg * DEG), np.sin(phi_deg * DEG), 0.])


# corners (red, green, blue) of the standard triangle in the orthonormal crystal frame and their labels
# cubic: corners as Miller vectors (not normalized) -> usual TSL color key: rgb ~ (z-x, x-y, y) for z>=x>=y>=0
LAUE_GROUPS = {
    'm-3m': {'ops': _cubic_ops(),
             'corners': np.array([[0, 0, 1.], [1, 0, 1.], [1, 1, 1.]]),
             'labels': ('[001]', '[101]', '[111]')},
    '6/mmm': {'ops': _closure([_rotz(60), _twofold([1, 0, 0]), -np.eye(3)]),
              'corners': np.array([[0, 0, 1.], _hexdir(0), _hexdir(30)]),
              'labels': ('[0001]', r'[10$\bar{1}$0]', r'[2$\bar{1}\bar{1}$0]')},
    '-3m1': {'ops': _closure([_rotz(120), _twofold(_hexdir(-30)), -np.eye(3)]),
             'corners': np.array([[0, 0, 1.], _hexdir(0), _hexdir(60)]),
             'labels': ('[0001]', r'[10$\bar{1}$0]', r'[01$\bar{1}$0]')},
    '4/mmm': {'ops': _closure([_rotz(90), _twofold([1, 0, 0]), -np.eye(3)]),
              'corners': np.array([[0, 0, 1.], [1, 0, 0], [1, 1, 0] / np.sqrt(2)]),
              'labels': ('[001]', '[100]', '[110]')},
    'mmm': {'ops': _closure([_twofold([1, 0, 0]), _twofold([0, 1, 0]), -np.eye(3)]),
            'corners': np.array([[0, 0, 1.], [1, 0, 0], [0, 1, 0]]),
            'labels': ('[001]', '[100]', '[010]')},
}


def guess_laue_group(latticeparameters: Sequence[float], tol: float = 1e-3) -> str:
    """Laue group of highest symmetry compatible with lattice parameters [a, b, c, alpha, beta, gamma]

    NB: trigonal crystals in hexagonal axes (e.g. Al2O3) give '6/mmm': use '-3m1' explicitly for them
    """
    a, b, c, alpha, beta, gamma = latticeparameters
    eq = lambda x, y: abs(x - y) <= tol * max(abs(x), abs(y))
    if eq(alpha, 90) and eq(beta, 90):
        if eq(gamma, 90):
            if eq(a, b) and eq(b, c):
                return 'm-3m'
            if eq(a, b):
                return '4/mmm'
            return 'mmm'
        if eq(gamma, 120) and eq(a, b):
            return '6/mmm'
    raise ValueError(f'lattice parameters {latticeparameters}: Laue group not supported for IPF colors '
                     f'(supported: {list(LAUE_GROUPS)})')


def laue_group_of_material(key_material: str, dictmaterials: Optional[dict] = None) -> str:
    """Laue group guessed from the lattice parameters of a material of the LaueTools dict (or of dictmaterials)"""
    if dictmaterials and key_material in dictmaterials:
        latticeparameters = dictmaterials[key_material][1]
    else:
        latticeparameters = DictLT.dict_Materials[key_material][1]
    group = guess_laue_group(latticeparameters)
    if group == '6/mmm':
        GT.printyellow(f"{key_material}: hexagonal lattice -> Laue group '6/mmm'. "
                       "For trigonal crystals (e.g. Al2O3, quartz) use '-3m1'")
    return group


# --------------------------------------------------------------------------------------
#  DIRECTIONS AND COLORS
# --------------------------------------------------------------------------------------
def orthonormalize(UB: np.ndarray) -> np.ndarray:
    """rotation closest to UB (polar decomposition), for (..., 3, 3) arrays. NaN matrices give NaN"""
    UB = np.asarray(UB, dtype=float)
    rot = np.full(UB.shape, np.nan)
    finite = np.all(np.isfinite(UB), axis=(-2, -1))
    if np.any(finite):
        u, _, vt = np.linalg.svd(UB[finite])
        rot[finite] = u @ vt
    return rot


def sample_rotation(anglesample: float = 40.) -> np.ndarray:
    """Rot such that q_sample = Rot q_lab (LaueGeometry.fromlab_tosample())"""
    c, s = np.cos(anglesample * DEG), np.sin(anglesample * DEG)
    return np.array([[c, 0, s], [0, 1., 0], [-s, 0, c]])


def sample_directions_in_crystal(UB: np.ndarray, sample_axis: Union[str, Sequence[float]] = 'z',
                                 anglesample: float = 40.) -> np.ndarray:
    """unit vectors (n, 3), in the orthonormal crystal frame, of the sample axis ('x', 'y', 'z' or vector in sample frame)

    UB: orientation matrices (n, 3, 3) (or (3, 3)) as written in .fit files (lab frame). NaN rows for NaN matrices
    """
    UB = np.asarray(UB, dtype=float).reshape(-1, 3, 3)
    axis = SAMPLE_AXES[sample_axis.lower()] if isinstance(sample_axis, str) else np.asarray(sample_axis, float)
    axis_lab = sample_rotation(anglesample).T @ (axis / np.linalg.norm(axis))
    rot = orthonormalize(UB)
    # q_lab = rot q_crystal  -> q_crystal = rot^T q_lab
    return np.einsum('nji,j->ni', rot, axis_lab)


def reduce_to_fundamental(directions: np.ndarray, laue_group: str) -> Tuple[np.ndarray, np.ndarray]:
    """bring crystal directions (n, 3) into the standard triangle of the Laue group

    Returns
    -------
    reduced directions (n, 3), barycentric weights (n, 3) on the triangle corners (>= 0). NaN for NaN input
    """
    group = LAUE_GROUPS[laue_group]
    directions = np.asarray(directions, dtype=float).reshape(-1, 3)
    invcorners = np.linalg.inv(group['corners'].T)
    equiv = np.einsum('oij,nj->oni', group['ops'], directions)       # (nops, n, 3)
    weights = np.einsum('ij,onj->oni', invcorners, equiv)            # (nops, n, 3)
    minweights = np.min(np.nan_to_num(weights, nan=-np.inf), axis=2)
    best = np.argmax(minweights, axis=0)                            # op with direction inside the triangle
    idx = np.arange(len(directions))
    return equiv[best, idx], weights[best, idx]


def ipf_colors(directions: np.ndarray, laue_group: str) -> np.ndarray:
    """RGB colors (n, 3) in [0, 1] of crystal directions (n, 3). NaN for NaN directions"""
    _, weights = reduce_to_fundamental(directions, laue_group)
    weights = np.clip(weights, 0, None)
    with np.errstate(invalid='ignore', divide='ignore'):
        return weights / np.max(weights, axis=1, keepdims=True)


def ipf_rgb_map(UB: np.ndarray, invmapdims: Tuple[int, int], laue_group: str, sample_axis='z',
                anglesample: float = 40., mask: Optional[np.ndarray] = None) -> np.ndarray:
    """IPF color map (nb rows, nb cols, 3) of the UB matrices of a map (invmapdims = (slow, fast))

    mask: boolean array (True = masked) of shape invmapdims. Masked or missing points are NaN
    """
    nbpoints = invmapdims[0] * invmapdims[1]
    dirs = sample_directions_in_crystal(np.asarray(UB)[:nbpoints], sample_axis, anglesample)
    rgb = ipf_colors(dirs, laue_group).reshape(invmapdims[0], invmapdims[1], 3)
    if mask is not None:
        rgb[np.asarray(mask, dtype=bool).reshape(invmapdims)] = np.nan
    return rgb


# --------------------------------------------------------------------------------------
#  PLOTS
# --------------------------------------------------------------------------------------
def _stereo(v: np.ndarray) -> np.ndarray:
    """stereographic projection (from south pole) of unit vectors (n, 3) with z >= 0"""
    v = v / np.linalg.norm(v, axis=-1, keepdims=True)
    return v[..., :2] / (1 + v[..., 2:3])


def _arc(v1, v2, nb=100) -> np.ndarray:
    """points of the great circle arc between v1 and v2"""
    v1, v2 = v1 / np.linalg.norm(v1), v2 / np.linalg.norm(v2)
    angle = np.arccos(np.clip(np.dot(v1, v2), -1, 1))
    t = np.linspace(0, 1, nb)[:, None]
    return (np.sin((1 - t) * angle) * v1 + np.sin(t * angle) * v2) / np.sin(angle)


def plot_ipf_key(laue_group: str, ax=None, directions: Optional[np.ndarray] = None, resolution: int = 400,
                 markersize: float = 2, markercolor='k', alpha: float = 0.3, title: Optional[str] = None):
    """color key of IPF maps in the standard triangle (stereographic projection)

    directions: optional crystal directions (n, 3) (e.g. sample_directions_in_crystal()) plotted as points
    """
    group = LAUE_GROUPS[laue_group]
    corners = group['corners'] / np.linalg.norm(group['corners'], axis=1, keepdims=True)
    if ax is None:
        _, ax = plt.subplots(figsize=(3.5, 3.5))

    # colored triangle: inverse stereographic projection of a grid
    edges = np.concatenate([_stereo(_arc(corners[i], corners[(i + 1) % 3])) for i in range(3)])
    xmin, ymin = edges.min(axis=0)
    xmax, ymax = edges.max(axis=0)
    X, Y = np.meshgrid(np.linspace(xmin, xmax, resolution), np.linspace(ymin, ymax, resolution))
    r2 = X ** 2 + Y ** 2
    vecs = np.stack([2 * X, 2 * Y, 1 - r2], axis=-1).reshape(-1, 3) / (1 + r2).reshape(-1, 1)
    weights = np.linalg.solve(group['corners'].T, vecs.T).T
    inside = np.all(weights >= -1e-9, axis=1)
    rgba = np.ones((len(vecs), 4))
    w = np.clip(weights[inside], 0, None)
    rgba[inside, :3] = w / w.max(axis=1, keepdims=True)
    rgba[~inside, 3] = 0
    ax.imshow(rgba.reshape(resolution, resolution, 4), origin='lower', extent=(xmin, xmax, ymin, ymax),
              interpolation='bilinear')
    ax.plot(edges[:, 0], edges[:, 1], 'k-', lw=1)

    if directions is not None:
        reduced, _ = reduce_to_fundamental(directions, laue_group)
        reduced = reduced[np.all(np.isfinite(reduced), axis=1)]
        if len(reduced):
            pts = _stereo(reduced)
            ax.plot(pts[:, 0], pts[:, 1], '.', ms=markersize, color=markercolor, alpha=alpha)

    # corner labels, placed outwards from the triangle center
    pcorners = _stereo(corners)
    center = pcorners.mean(axis=0)
    span = max(xmax - xmin, ymax - ymin)
    for pc, label in zip(pcorners, group['labels']):
        offset = pc - center
        offset = 0.04 * span * offset / (np.linalg.norm(offset) + 1e-12)
        ha = 'right' if offset[0] < -0.01 * span else ('left' if offset[0] > 0.01 * span else 'center')
        va = 'top' if offset[1] < -0.01 * span else ('bottom' if offset[1] > 0.01 * span else 'center')
        ax.text(*(pc + offset), label, ha=ha, va=va, fontsize=10)
    ax.set_xlim(xmin - 0.15 * span, xmax + 0.15 * span)
    ax.set_ylim(ymin - 0.12 * span, ymax + 0.12 * span)
    ax.set_aspect('equal')
    ax.axis('off')
    ax.set_title(title if title is not None else laue_group, fontsize=10)
    return ax


def plot_ipf_maps(UB: np.ndarray, invmapdims: Tuple[int, int], laue_group: str,
                  sample_axes: Iterable[str] = ('x', 'y', 'z'), anglesample: float = 40.,
                  mask: Optional[np.ndarray] = None, bad_color='black',
                  xlabel: str = 'fast axis', ylabel: str = 'slow axis', show_directions: bool = True,
                  figsize=None) -> Tuple[plt.Figure, np.ndarray, Dict[str, np.ndarray]]:
    """IPF color maps along sample axes + color key (with the measured directions of the last sample axis)

    UB: (n, 3, 3) orientation matrices of the map (e.g. parsed_fitfileseries.UB), n >= invmapdims[0] * invmapdims[1]
    mask: (True = masked) array of shape invmapdims, masked and missing points are drawn with bad_color

    Returns fig, axes, {sample axis: rgb map (nb rows, nb cols, 3)}
    """
    sample_axes = list(sample_axes)
    nmaps = len(sample_axes)
    if figsize is None:
        figsize = (3.6 * nmaps + 3, 3.8)
    fig, axes = plt.subplots(1, nmaps + 1, figsize=figsize,
                             gridspec_kw={'width_ratios': [1] * nmaps + [0.8]})
    rgbmaps = {}
    for ax, sample_axis in zip(axes, sample_axes):
        rgb = ipf_rgb_map(UB, invmapdims, laue_group, sample_axis, anglesample, mask)
        rgbmaps[sample_axis] = rgb
        rgba = np.ones(rgb.shape[:2] + (4,))
        rgba[..., :3] = np.nan_to_num(rgb)
        rgba[..., 3] = np.all(np.isfinite(rgb), axis=2)   # masked and missing points: transparent
        ax.set_facecolor(bad_color)
        ax.imshow(rgba, origin='lower', interpolation='nearest')
        ax.set_title(f'IPF-{sample_axis.upper()} (sample frame)', fontsize=10)
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.format_coord = lambda x, y: GT.format_getimageindex_imshow(x, y, invmapdims)

    directions = None
    if show_directions:
        directions = sample_directions_in_crystal(np.asarray(UB)[:invmapdims[0] * invmapdims[1]],
                                                  sample_axes[-1], anglesample)
        if mask is not None:
            directions = directions[~np.asarray(mask, dtype=bool).ravel()]
    plot_ipf_key(laue_group, ax=axes[-1], directions=directions,
                 title=f'{laue_group}' + (f'  (points: IPF-{sample_axes[-1].upper()})' if show_directions else ''))
    fig.tight_layout()
    return fig, axes, rgbmaps
